from __future__ import annotations

from pathlib import Path
import re


_VERSION_PATTERN = re.compile(r'^__version__\s*=\s*["\']([^"\']+)["\']', re.MULTILINE)

BASE_HIDDEN_IMPORTS = (
    "PyQt6",
    "PyQt6.QtWidgets",
    "PyQt6.QtCore",
    "pystray",
    "PIL",
    "psutil",
    "requests",
    "openpyxl",
    "formulas",
)


def read_app_version(project_root: Path) -> str:
    version_file = project_root / "modules" / "version.py"
    payload = version_file.read_text(encoding="utf-8")
    match = _VERSION_PATTERN.search(payload)
    if match is None:
        raise RuntimeError(f"Unable to parse app version from {version_file}")
    return match.group(1).strip()


def write_installer_version_include(project_root: Path) -> Path:
    version = read_app_version(project_root)
    output = project_root / "packaging" / "inno-setup" / "version.auto.iss"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        (
            "; Auto-generated by scripts/build_support.py / build scripts\n"
            f'#define MyAppVersion "{version}"\n'
        ),
        encoding="utf-8",
    )
    return output


def collect_hidden_imports() -> list[str]:
    imports = list(BASE_HIDDEN_IMPORTS)

    try:
        from PyInstaller.utils.hooks import collect_submodules
        imports.extend(collect_submodules("formulas"))
    except Exception:
        return imports

    return list(dict.fromkeys(imports))
