from __future__ import annotations

from datetime import datetime, timezone
import hashlib
from importlib import metadata
import json
import os
from pathlib import Path
import platform
import re
import shutil
import ssl
import struct
import subprocess
import sys
from typing import Any
from urllib.parse import urlsplit


APP_DISPLAY_NAME = "Textile Device Client"
APP_PUBLISHER = "Textile Device Monitor"
EXECUTABLE_NAME = "textile-device-client.exe"
BUILD_MANIFEST_NAME = "build-manifest.json"
BUILD_LOCK_NAME = "requirements-build.lock.txt"
BUILD_MANIFEST_SCHEMA = 2
CLIENT_BUILD_DEFAULTS_NAME = "client-build-defaults.json"
PACKAGED_CA_RELATIVE_PATH = Path("certs") / "inspection-root-ca.pem"
PRODUCTION_HOSTNAME = "textile-monitor.internal"
DEFAULT_SERVER_URL = "https://textile-monitor.internal"
CLIENT_ADMIN_TOOL_NAMES = (
    "migrate_to_internal_https.ps1",
    "verify_client_https_reporting.ps1",
)
SHARED_ADMIN_TOOL_NAMES = (
    "Install-InspectionTlsTrust.ps1",
    "Restore-InspectionTlsTrust.ps1",
    "InspectionTls.Common.ps1",
)
ADMIN_TOOL_NAMES = CLIENT_ADMIN_TOOL_NAMES + SHARED_ADMIN_TOOL_NAMES
SUPPORTED_PYTHON = (3, 12)
DEFAULT_TIMESTAMP_URL = "http://timestamp.digicert.com"

_VERSION_PATTERN = re.compile(r'^__version__\s*=\s*["\']([^"\']+)["\']', re.MULTILINE)
_PINNED_REQUIREMENT_PATTERN = re.compile(
    r"^([A-Za-z0-9_.-]+)==([A-Za-z0-9_.+!-]+)$"
)
_PEM_CERTIFICATE_PATTERN = re.compile(
    rb"-----BEGIN CERTIFICATE-----\s*"
    rb"[A-Za-z0-9+/=\r\n]+?"
    rb"\s*-----END CERTIFICATE-----"
)
_PEM_PRIVATE_KEY_PATTERN = re.compile(
    rb"-----BEGIN [^\r\n-]*PRIVATE KEY-----"
)

BASE_HIDDEN_IMPORTS = (
    "PyQt6",
    "PyQt6.QtWidgets",
    "PyQt6.QtCore",
    "pystray",
    "PIL",
    "psutil",
    "requests",
    "openpyxl",
    "formulas",
)

FORMULAS_EXCLUDED_PREFIXES = (
    "formulas.app",
    "formulas.cli",
    "formulas.excel.ods_reader",
)

_REQUIRED_BUILD_INPUTS = (
    Path("main.py"),
    Path("requirements.txt"),
    Path(BUILD_LOCK_NAME),
    Path("modules/version.py"),
    Path("resources/icon.ico"),
    Path("packaging/inno-setup/textile_device_client.iss"),
    Path("packaging/pyinstaller/textile_device_client.spec"),
    Path("scripts/build_support.py"),
    Path("scripts/build_windows_installer.py"),
    Path("scripts/build_windows_onedir.py"),
    Path("scripts/build_windows_release.py"),
    Path("scripts/migrate_to_internal_https.ps1"),
    Path("scripts/verify_client_https_reporting.ps1"),
)

_BUILD_INPUT_TREES = (
    Path("modules"),
    Path("resources"),
    Path("packaging/pyinstaller"),
)


class BuildValidationError(RuntimeError):
    pass


def _distribution_version(name: str) -> str:
    try:
        return metadata.version(name)
    except metadata.PackageNotFoundError:
        # Real builds call ensure_build_environment() first. This fallback keeps
        # manifest helpers usable for isolated unit tests and diagnostics.
        return "not-installed"


def read_app_version(project_root: Path) -> str:
    version_file = project_root / "modules" / "version.py"
    payload = version_file.read_text(encoding="utf-8")
    match = _VERSION_PATTERN.search(payload)
    if match is None:
        raise RuntimeError(f"Unable to parse app version from {version_file}")
    return match.group(1).strip()


def write_installer_version_include(project_root: Path) -> Path:
    version = read_app_version(project_root)
    output = project_root / "packaging" / "inno-setup" / "version.auto.iss"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        (
            "; Auto-generated by scripts/build_support.py / build scripts\n"
            f'#define MyAppVersion "{version}"\n'
        ),
        encoding="utf-8",
    )
    return output


def _windows_version_tuple(version: str) -> tuple[int, int, int, int]:
    parts = version.split(".")
    if not 1 <= len(parts) <= 4 or any(not part.isdigit() for part in parts):
        raise BuildValidationError(
            f"App version must contain 1-4 numeric components: {version!r}"
        )
    values = [int(part) for part in parts]
    if any(value > 65535 for value in values):
        raise BuildValidationError(
            f"App version components must be <= 65535: {version!r}"
        )
    return tuple((values + [0, 0, 0, 0])[:4])


def write_pyinstaller_version_file(project_root: Path, output: Path) -> Path:
    version = read_app_version(project_root)
    version_tuple = _windows_version_tuple(version)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        f"""# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={version_tuple},
    prodvers={version_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', '{APP_PUBLISHER}'),
          StringStruct('FileDescription', '{APP_DISPLAY_NAME}'),
          StringStruct('FileVersion', '{version}'),
          StringStruct('InternalName', '{EXECUTABLE_NAME}'),
          StringStruct('OriginalFilename', '{EXECUTABLE_NAME}'),
          StringStruct('ProductName', '{APP_DISPLAY_NAME}'),
          StringStruct('ProductVersion', '{version}')
        ]
      )
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""",
        encoding="utf-8",
    )
    return output


def _include_formulas_submodule(module_name: str) -> bool:
    return not any(
        module_name == prefix or module_name.startswith(f"{prefix}.")
        for prefix in FORMULAS_EXCLUDED_PREFIXES
    )


def collect_hidden_imports() -> list[str]:
    from PyInstaller.utils.hooks import collect_submodules

    imports = list(BASE_HIDDEN_IMPORTS)
    imports.extend(
        collect_submodules("formulas", filter=_include_formulas_submodule)
    )
    return list(dict.fromkeys(imports))


def _canonicalize_distribution_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def read_build_lock(project_root: Path) -> dict[str, tuple[str, str]]:
    lock_path = project_root / BUILD_LOCK_NAME
    if not lock_path.exists():
        raise BuildValidationError(f"Build dependency lock not found: {lock_path}")

    locked: dict[str, tuple[str, str]] = {}
    for line_number, raw_line in enumerate(
        lock_path.read_text(encoding="utf-8").splitlines(), start=1
    ):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        match = _PINNED_REQUIREMENT_PATTERN.fullmatch(line)
        if match is None:
            raise BuildValidationError(
                f"Every build dependency must be exactly pinned; "
                f"{lock_path}:{line_number}: {line!r}"
            )
        distribution_name, expected_version = match.groups()
        canonical_name = _canonicalize_distribution_name(distribution_name)
        if canonical_name in locked:
            raise BuildValidationError(
                f"Duplicate dependency in {lock_path}: {distribution_name}"
            )
        locked[canonical_name] = (distribution_name, expected_version)
    if not locked:
        raise BuildValidationError(f"Build dependency lock is empty: {lock_path}")
    return locked


def validate_build_environment(project_root: Path) -> list[str]:
    errors: list[str] = []
    if sys.platform != "win32":
        errors.append(f"Windows is required, current platform is {sys.platform!r}")
    if sys.version_info[:2] != SUPPORTED_PYTHON:
        errors.append(
            "CPython "
            f"{SUPPORTED_PYTHON[0]}.{SUPPORTED_PYTHON[1]} is required, "
            f"current version is {platform.python_version()}"
        )
    if struct.calcsize("P") * 8 != 64:
        errors.append("A 64-bit Python interpreter is required")

    try:
        locked = read_build_lock(project_root)
    except BuildValidationError as exc:
        errors.append(str(exc))
        return errors

    for distribution_name, expected_version in locked.values():
        try:
            actual_version = metadata.version(distribution_name)
        except metadata.PackageNotFoundError:
            errors.append(f"Missing build dependency: {distribution_name}=={expected_version}")
            continue
        if actual_version != expected_version:
            errors.append(
                f"Build dependency mismatch: {distribution_name} "
                f"is {actual_version}, expected {expected_version}"
            )
    return errors


def ensure_build_environment(project_root: Path) -> None:
    errors = validate_build_environment(project_root)
    if errors:
        details = "\n".join(f"  - {error}" for error in errors)
        raise BuildValidationError(
            "Build environment validation failed:\n"
            f"{details}\n"
            f"Install the locked environment with: "
            f"python -m pip install -r {BUILD_LOCK_NAME}"
        )


def create_isolated_build_environment() -> dict[str, str]:
    """Create a deterministic DLL search path for the PyInstaller child."""
    environment = os.environ.copy()
    windows_directory = Path(environment.get("WINDIR", r"C:\Windows"))
    path_candidates = (
        Path(sys.executable).parent,
        Path(sys.prefix),
        Path(sys.base_prefix),
        Path(sys.base_prefix) / "DLLs",
        windows_directory / "System32",
        windows_directory,
    )
    unique_paths: list[str] = []
    seen_paths: set[str] = set()
    for path in path_candidates:
        normalized = os.path.normcase(os.path.abspath(path))
        if normalized in seen_paths:
            continue
        seen_paths.add(normalized)
        unique_paths.append(str(path))

    environment["PATH"] = os.pathsep.join(unique_paths)
    environment["PYTHONNOUSERSITE"] = "1"
    environment.pop("PYTHONPATH", None)
    return environment


def collect_build_input_files(project_root: Path) -> list[Path]:
    missing = [
        project_root / relative_path
        for relative_path in _REQUIRED_BUILD_INPUTS
        if not (project_root / relative_path).is_file()
    ]
    if missing:
        formatted = "\n".join(f"  - {path}" for path in missing)
        raise BuildValidationError(f"Required build inputs are missing:\n{formatted}")

    files = {project_root / path for path in _REQUIRED_BUILD_INPUTS}
    for relative_tree in _BUILD_INPUT_TREES:
        tree = project_root / relative_tree
        if not tree.is_dir():
            continue
        for path in tree.rglob("*"):
            if not path.is_file():
                continue
            if "__pycache__" in path.parts or path.suffix in {".pyc", ".pyo"}:
                continue
            files.add(path)
    return sorted(files, key=lambda path: path.relative_to(project_root).as_posix())


def calculate_source_fingerprint(project_root: Path) -> str:
    digest = hashlib.sha256()
    for path in collect_build_input_files(project_root):
        relative_path = path.relative_to(project_root).as_posix()
        digest.update(relative_path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_sha256_file(path: Path, output: Path | None = None) -> Path:
    output_path = output or path.with_name(f"{path.name}.sha256")
    output_path.write_text(
        f"{sha256_file(path)}  {path.name}\n",
        encoding="ascii",
    )
    return output_path


def validate_packaged_root_ca(path: Path) -> None:
    """Require one valid, public, self-signed RSA-3072 root CA certificate."""

    try:
        from cryptography import x509
        from cryptography.exceptions import InvalidSignature, UnsupportedAlgorithm
        from cryptography.hazmat.primitives.asymmetric import rsa
    except ImportError as exc:
        raise BuildValidationError(
            "The locked Windows build environment is missing cryptography; "
            f"install {BUILD_LOCK_NAME} before packaging the client."
        ) from exc

    try:
        pem_payload = path.read_bytes()
    except OSError as exc:
        raise BuildValidationError(f"Unable to read TLS CA bundle: {path}") from exc
    if _PEM_PRIVATE_KEY_PATTERN.search(pem_payload):
        raise BuildValidationError(
            "TLS CA bundle must contain public certificates only, never a private key"
        )
    certificates = list(_PEM_CERTIFICATE_PATTERN.finditer(pem_payload))
    if len(certificates) != 1:
        raise BuildValidationError(
            "Production client TLS CA bundle must contain exactly one root certificate"
        )
    remainder = (
        pem_payload[: certificates[0].start()]
        + pem_payload[certificates[0].end() :]
    )
    if remainder.strip():
        raise BuildValidationError(
            "TLS CA bundle contains content outside the root certificate"
        )

    try:
        certificate = x509.load_pem_x509_certificate(certificates[0].group(0))
    except ValueError as exc:
        raise BuildValidationError(
            f"TLS CA bundle contains an invalid X.509 certificate: {path}"
        ) from exc
    if certificate.subject != certificate.issuer:
        raise BuildValidationError("Packaged CA certificate must be self-issued")
    try:
        certificate.verify_directly_issued_by(certificate)
    except (InvalidSignature, UnsupportedAlgorithm, TypeError, ValueError) as exc:
        raise BuildValidationError(
            "Packaged CA certificate is not cryptographically self-signed"
        ) from exc
    try:
        constraints = certificate.extensions.get_extension_for_class(
            x509.BasicConstraints
        )
    except x509.ExtensionNotFound as exc:
        raise BuildValidationError(
            "Packaged CA certificate is missing Basic Constraints"
        ) from exc
    if not constraints.critical or not constraints.value.ca:
        raise BuildValidationError(
            "Packaged CA certificate must declare critical CA:TRUE"
        )
    public_key = certificate.public_key()
    if not isinstance(public_key, rsa.RSAPublicKey) or public_key.key_size != 3072:
        raise BuildValidationError(
            "Packaged root CA must use a 3072-bit RSA public key"
        )

    now = datetime.now(timezone.utc)
    if (
        now < certificate.not_valid_before_utc
        or now >= certificate.not_valid_after_utc
    ):
        raise BuildValidationError(
            "Packaged root CA is not currently valid"
        )


def normalize_production_server_url(value: str) -> str:
    """Validate the immutable hostname/port contract of production packages."""

    raw_url = value.strip()
    if "\\" in raw_url or "?" in raw_url or "#" in raw_url:
        raise BuildValidationError(
            "--default-server-url must not contain backslashes, query markers, "
            "or fragment markers"
        )
    try:
        parsed = urlsplit(raw_url)
        port = parsed.port
    except ValueError as exc:
        raise BuildValidationError(f"Invalid --default-server-url: {exc}") from exc
    if (
        parsed.scheme.lower() != "https"
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.path not in {"", "/"}
        or parsed.query
        or parsed.fragment
    ):
        raise BuildValidationError(
            "--default-server-url must be a pure HTTPS origin without "
            "credentials, /api, query, or fragment"
        )
    if parsed.hostname.lower() != PRODUCTION_HOSTNAME or port not in {None, 443}:
        raise BuildValidationError(
            "Production client packages must use exactly "
            f"https://{PRODUCTION_HOSTNAME} on port 443"
        )
    return DEFAULT_SERVER_URL


def prepare_tls_build_assets(
    generated_path: Path,
    *,
    default_server_url: str,
    tls_ca_bundle: Path,
) -> tuple[Path, Path]:
    """Validate and stage production TLS defaults for PyInstaller."""

    normalized_url = normalize_production_server_url(default_server_url)

    ca_source = tls_ca_bundle.expanduser().resolve(strict=False)
    if not ca_source.is_file():
        raise BuildValidationError(
            f"TLS CA bundle not found: {ca_source}. Pass --tls-ca-bundle."
        )
    try:
        ssl.create_default_context(cafile=str(ca_source))
    except (OSError, ssl.SSLError) as exc:
        raise BuildValidationError(
            f"TLS CA bundle is invalid: {ca_source}"
        ) from exc
    validate_packaged_root_ca(ca_source)

    generated_path.mkdir(parents=True, exist_ok=True)
    defaults_path = generated_path / CLIENT_BUILD_DEFAULTS_NAME
    staged_ca_path = generated_path / PACKAGED_CA_RELATIVE_PATH.name
    defaults_path.write_text(
        json.dumps(
            {
                "config_schema_version": 2,
                "server_url": normalized_url,
                "transport_security": "required",
                "tls_ca_bundle": PACKAGED_CA_RELATIVE_PATH.as_posix(),
            },
            ensure_ascii=True,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    shutil.copy2(ca_source, staged_ca_path)
    return defaults_path, staged_ca_path


def read_packaged_tls_metadata(app_dir: Path) -> dict[str, Any]:
    defaults_path = app_dir / CLIENT_BUILD_DEFAULTS_NAME
    if not defaults_path.is_file():
        raise BuildValidationError(
            f"Packaged client defaults not found: {defaults_path}"
        )
    try:
        defaults = json.loads(defaults_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise BuildValidationError(
            f"Invalid packaged client defaults: {defaults_path}"
        ) from exc
    if defaults.get("config_schema_version") != 2:
        raise BuildValidationError("Packaged client config schema must be 2")
    if defaults.get("transport_security") != "required":
        raise BuildValidationError(
            "Production package must default to required transport security"
        )
    server_url = str(defaults.get("server_url") or "")
    try:
        normalized_url = normalize_production_server_url(server_url)
    except BuildValidationError as exc:
        raise BuildValidationError(
            f"Packaged default server URL is invalid: {exc}"
        ) from exc
    if server_url != normalized_url:
        raise BuildValidationError(
            f"Packaged default server URL must be exactly {DEFAULT_SERVER_URL}"
        )
    ca_relative = Path(str(defaults.get("tls_ca_bundle") or ""))
    if ca_relative.is_absolute() or ".." in ca_relative.parts:
        raise BuildValidationError("Packaged TLS CA path must be a safe relative path")
    ca_path = app_dir / ca_relative
    if not ca_path.is_file():
        raise BuildValidationError(f"Packaged TLS CA bundle not found: {ca_path}")
    validate_packaged_root_ca(ca_path)
    return {
        "defaults": defaults,
        "ca_path": ca_path,
        "ca_sha256": sha256_file(ca_path),
    }


def read_packaged_admin_tool_hashes(app_dir: Path) -> dict[str, str]:
    tools_directory = app_dir / "admin-tools"
    hashes: dict[str, str] = {}
    for name in ADMIN_TOOL_NAMES:
        path = tools_directory / name
        if not path.is_file():
            raise BuildValidationError(f"Packaged admin tool not found: {path}")
        hashes[name] = sha256_file(path)
    return hashes


def create_build_manifest(
    project_root: Path,
    app_dir: Path,
    *,
    console: bool,
    bootloader_debug: bool,
    signed: bool,
) -> dict[str, Any]:
    executable = app_dir / EXECUTABLE_NAME
    if not executable.is_file():
        raise BuildValidationError(f"Built executable not found: {executable}")
    tls_metadata = read_packaged_tls_metadata(app_dir)
    admin_tool_hashes = read_packaged_admin_tool_hashes(app_dir)
    return {
        "schema": BUILD_MANIFEST_SCHEMA,
        "app_name": APP_DISPLAY_NAME,
        "app_version": read_app_version(project_root),
        "build_mode": "console" if console else "release",
        "bootloader_debug": bool(bootloader_debug),
        "signed": bool(signed),
        "executable_name": EXECUTABLE_NAME,
        "executable_sha256": sha256_file(executable),
        "source_sha256": calculate_source_fingerprint(project_root),
        "python_version": platform.python_version(),
        "python_architecture": f"{struct.calcsize('P') * 8}-bit",
        "pyinstaller_version": _distribution_version("PyInstaller"),
        "requests_version": _distribution_version("requests"),
        "certifi_version": _distribution_version("certifi"),
        "cryptography_version": _distribution_version("cryptography"),
        "default_server_url": tls_metadata["defaults"]["server_url"],
        "transport_security": tls_metadata["defaults"]["transport_security"],
        "tls_ca_bundle": tls_metadata["defaults"]["tls_ca_bundle"],
        "tls_ca_sha256": tls_metadata["ca_sha256"],
        "admin_tools_sha256": admin_tool_hashes,
    }


def write_build_manifest(
    project_root: Path,
    app_dir: Path,
    *,
    console: bool,
    bootloader_debug: bool,
    signed: bool,
) -> Path:
    manifest = create_build_manifest(
        project_root,
        app_dir,
        console=console,
        bootloader_debug=bootloader_debug,
        signed=signed,
    )
    output = app_dir / BUILD_MANIFEST_NAME
    output.write_text(
        json.dumps(manifest, ensure_ascii=True, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return output


def validate_release_build(
    project_root: Path,
    app_dir: Path,
    *,
    require_signed: bool = False,
) -> dict[str, Any]:
    manifest_path = app_dir / BUILD_MANIFEST_NAME
    if not manifest_path.is_file():
        raise BuildValidationError(
            f"Build manifest not found: {manifest_path}. Rebuild the onedir package."
        )
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise BuildValidationError(f"Invalid build manifest: {manifest_path}: {exc}") from exc

    errors: list[str] = []
    expected_version = read_app_version(project_root)
    expected_source_hash = calculate_source_fingerprint(project_root)
    executable = app_dir / EXECUTABLE_NAME
    try:
        tls_metadata = read_packaged_tls_metadata(app_dir)
        admin_tool_hashes = read_packaged_admin_tool_hashes(app_dir)
    except BuildValidationError as exc:
        tls_metadata = None
        admin_tool_hashes = None
        errors = [str(exc)]
    else:
        errors = []

    if manifest.get("schema") != BUILD_MANIFEST_SCHEMA:
        errors.append("unsupported build manifest schema")
    if manifest.get("app_version") != expected_version:
        errors.append(
            f"binary version is {manifest.get('app_version')!r}, "
            f"source version is {expected_version!r}"
        )
    if manifest.get("source_sha256") != expected_source_hash:
        errors.append("source files changed after the onedir package was built")
    if manifest.get("build_mode") != "release":
        errors.append(f"build mode is {manifest.get('build_mode')!r}, expected 'release'")
    if manifest.get("bootloader_debug") is not False:
        errors.append("bootloader debug is enabled")
    if require_signed and manifest.get("signed") is not True:
        errors.append("the onedir executable is not signed")
    if not executable.is_file():
        errors.append(f"executable not found: {executable}")
    elif manifest.get("executable_sha256") != sha256_file(executable):
        errors.append("executable hash does not match the build manifest")
    if tls_metadata is not None:
        defaults = tls_metadata["defaults"]
        if manifest.get("default_server_url") != defaults.get("server_url"):
            errors.append("default server URL does not match packaged defaults")
        if manifest.get("transport_security") != "required":
            errors.append("packaged transport security is not required")
        if manifest.get("tls_ca_sha256") != tls_metadata["ca_sha256"]:
            errors.append("packaged TLS CA hash does not match the build manifest")
    if (
        admin_tool_hashes is not None
        and manifest.get("admin_tools_sha256") != admin_tool_hashes
    ):
        errors.append("packaged admin tool hashes do not match the build manifest")

    if errors:
        details = "\n".join(f"  - {error}" for error in errors)
        raise BuildValidationError(
            "PyInstaller output is not a valid release build:\n"
            f"{details}\n"
            "Run scripts/build_windows_release.py or rebuild the release onedir package."
        )
    return manifest


def find_signtool(explicit_path: str | None = None) -> str | None:
    configured_path = explicit_path or os.environ.get("SIGNTOOL_EXE", "").strip()
    if configured_path:
        candidate = Path(configured_path).expanduser()
        if candidate.is_file():
            return str(candidate)
        return None

    resolved = shutil.which("signtool.exe") or shutil.which("signtool")
    if resolved:
        return resolved

    program_files_x86 = os.environ.get("ProgramFiles(x86)", "").strip()
    if not program_files_x86:
        return None
    kits_bin = Path(program_files_x86) / "Windows Kits" / "10" / "bin"
    if not kits_bin.is_dir():
        return None
    candidates = sorted(
        kits_bin.glob("*/x64/signtool.exe"),
        key=lambda path: path.parent.parent.name,
        reverse=True,
    )
    return str(candidates[0]) if candidates else None


def sign_windows_file(
    path: Path,
    *,
    signtool_path: str | None = None,
    certificate_thumbprint: str | None = None,
    timestamp_url: str = DEFAULT_TIMESTAMP_URL,
) -> None:
    resolved_signtool = find_signtool(signtool_path)
    if not resolved_signtool:
        raise BuildValidationError(
            "signtool.exe was not found. Set SIGNTOOL_EXE or pass --signtool."
        )
    thumbprint = (
        certificate_thumbprint
        or os.environ.get("TDC_SIGN_CERT_THUMBPRINT", "")
    ).replace(" ", "").strip()
    if not thumbprint:
        raise BuildValidationError(
            "A signing certificate thumbprint is required. Set "
            "TDC_SIGN_CERT_THUMBPRINT or pass --certificate-thumbprint."
        )
    if not path.is_file():
        raise BuildValidationError(f"File to sign not found: {path}")

    command = [
        resolved_signtool,
        "sign",
        "/sha1",
        thumbprint,
        "/fd",
        "SHA256",
    ]
    if timestamp_url:
        command.extend(["/tr", timestamp_url, "/td", "SHA256"])
    command.append(str(path))
    subprocess.run(command, check=True)
    verify_windows_signature(path, signtool_path=resolved_signtool)


def verify_windows_signature(
    path: Path,
    *,
    signtool_path: str | None = None,
) -> None:
    resolved_signtool = find_signtool(signtool_path)
    if not resolved_signtool:
        raise BuildValidationError(
            "signtool.exe was not found. Set SIGNTOOL_EXE or pass --signtool."
        )
    if not path.is_file():
        raise BuildValidationError(f"Signed file not found: {path}")
    subprocess.run([resolved_signtool, "verify", "/pa", str(path)], check=True)
