"""legacy schema baseline

Revision ID: 0001_legacy_baseline
Revises:
Create Date: 2026-07-25 19:37:49.840795
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0001_legacy_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('folder_name', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('model_file', sa.String(length=255), nullable=False),
    sa.Column('root_path', sa.Text(), nullable=False),
    sa.Column('output_dir', sa.Text(), nullable=False),
    sa.Column('overlay_dir', sa.Text(), nullable=False),
    sa.Column('result_json_path', sa.Text(), nullable=False),
    sa.Column('excel_path', sa.Text(), nullable=False),
    sa.Column('infer_url', sa.String(length=500), nullable=False),
    sa.Column('infer_timeout_sec', sa.Integer(), nullable=False),
    sa.Column('inference_options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_images', sa.Integer(), nullable=False),
    sa.Column('processed_images', sa.Integer(), nullable=False),
    sa.Column('succeeded_images', sa.Integer(), nullable=False),
    sa.Column('failed_images', sa.Integer(), nullable=False),
    sa.Column('engine_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('summary_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('detail_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_jobs_created_at'), 'area_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_area_jobs_folder_name'), 'area_jobs', ['folder_name'], unique=False)
    op.create_index(op.f('ix_area_jobs_id'), 'area_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_area_jobs_job_id'), 'area_jobs', ['job_id'], unique=True)
    op.create_index(op.f('ix_area_jobs_status'), 'area_jobs', ['status'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OFFLINE', 'IDLE', 'BUSY', 'MAINTENANCE', 'ERROR', name='devicestatus'), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('task_name', sa.String(length=200), nullable=True),
    sa.Column('task_progress', sa.Integer(), nullable=True),
    sa.Column('task_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_elapsed_seconds', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('client_base_url', sa.String(length=200), nullable=True),
    sa.Column('queue_timeout_active_id', sa.Integer(), nullable=True),
    sa.Column('queue_timeout_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queue_timeout_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queue_timeout_reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queue_timeout_extended_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_code'), 'devices', ['device_code'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_config_key'), 'system_configs', ['config_key'], unique=True)
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_table('area_job_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=255), nullable=False),
    sa.Column('overlay_filename', sa.String(length=255), nullable=False),
    sa.Column('source_image_path', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('total_area_px', sa.Integer(), nullable=False),
    sa.Column('per_class_area_px', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('edited_by_id', sa.String(length=64), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edit_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['area_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'image_name', name='uq_area_job_image')
    )
    op.create_index(op.f('ix_area_job_images_created_at'), 'area_job_images', ['created_at'], unique=False)
    op.create_index(op.f('ix_area_job_images_id'), 'area_job_images', ['id'], unique=False)
    op.create_index(op.f('ix_area_job_images_job_id'), 'area_job_images', ['job_id'], unique=False)
    op.create_table('device_state_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task_key', sa.String(length=500), nullable=True),
    sa.Column('task_name', sa.String(length=200), nullable=True),
    sa.Column('task_progress', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_state_events_device_id'), 'device_state_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_state_events_event_type'), 'device_state_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_device_state_events_id'), 'device_state_events', ['id'], unique=False)
    op.create_index(op.f('ix_device_state_events_occurred_at'), 'device_state_events', ['occurred_at'], unique=False)
    op.create_table('device_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('task_name', sa.String(length=200), nullable=True),
    sa.Column('inspector_name', sa.String(length=50), nullable=True),
    sa.Column('task_progress', sa.Integer(), nullable=True),
    sa.Column('task_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('device_metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_status_history_id'), 'device_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_device_status_history_reported_at'), 'device_status_history', ['reported_at'], unique=False)
    op.create_table('device_status_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'report_id', name='uq_device_status_reports_device_report')
    )
    op.create_index(op.f('ix_device_status_reports_device_id'), 'device_status_reports', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_status_reports_id'), 'device_status_reports', ['id'], unique=False)
    op.create_index(op.f('ix_device_status_reports_processed_at'), 'device_status_reports', ['processed_at'], unique=False)
    op.create_table('device_task_states',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('task_key', sa.String(length=500), nullable=True),
    sa.Column('task_name', sa.String(length=200), nullable=True),
    sa.Column('observed_in_progress', sa.Boolean(), nullable=False),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('last_progress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index(op.f('ix_device_task_states_task_key'), 'device_task_states', ['task_key'], unique=False)
    op.create_table('queue_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspector_name', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('WAITING', 'COMPLETED', name='taskstatus'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('auto_remove_when_inactive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_records_id'), 'queue_records', ['id'], unique=False)
    op.create_index('uq_queue_records_waiting_device_position', 'queue_records', ['device_id', 'position'], unique=True, postgresql_where=sa.text("status = 'WAITING'"), sqlite_where=sa.text("status = 'WAITING'"))
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('stat_type', sa.String(length=20), nullable=False),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.Column('completed_tasks', sa.Integer(), nullable=True),
    sa.Column('failed_tasks', sa.Integer(), nullable=True),
    sa.Column('avg_duration', sa.Integer(), nullable=True),
    sa.Column('max_duration', sa.Integer(), nullable=True),
    sa.Column('min_duration', sa.Integer(), nullable=True),
    sa.Column('utilization_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_id'), 'statistics', ['id'], unique=False)
    op.create_table('area_job_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('bbox', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('polygon', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('area_px', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('initial_bbox', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('initial_polygon', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('initial_class_name', sa.String(length=100), nullable=True),
    sa.Column('initial_area_px', sa.Integer(), nullable=False),
    sa.Column('initial_is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['area_job_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_area_job_instances_created_at'), 'area_job_instances', ['created_at'], unique=False)
    op.create_index(op.f('ix_area_job_instances_id'), 'area_job_instances', ['id'], unique=False)
    op.create_index(op.f('ix_area_job_instances_image_id'), 'area_job_instances', ['image_id'], unique=False)
    op.create_table('queue_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('old_position', sa.Integer(), nullable=True),
    sa.Column('new_position', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.String(length=50), nullable=True),
    sa.Column('changed_by_id', sa.String(length=64), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('change_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['queue_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_change_logs_id'), 'queue_change_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_change_logs_id'), table_name='queue_change_logs')
    op.drop_table('queue_change_logs')
    op.drop_index(op.f('ix_area_job_instances_image_id'), table_name='area_job_instances')
    op.drop_index(op.f('ix_area_job_instances_id'), table_name='area_job_instances')
    op.drop_index(op.f('ix_area_job_instances_created_at'), table_name='area_job_instances')
    op.drop_table('area_job_instances')
    op.drop_index(op.f('ix_statistics_id'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_index('uq_queue_records_waiting_device_position', table_name='queue_records', postgresql_where=sa.text("status = 'WAITING'"), sqlite_where=sa.text("status = 'WAITING'"))
    op.drop_index(op.f('ix_queue_records_id'), table_name='queue_records')
    op.drop_table('queue_records')
    op.drop_index(op.f('ix_device_task_states_task_key'), table_name='device_task_states')
    op.drop_table('device_task_states')
    op.drop_index(op.f('ix_device_status_reports_processed_at'), table_name='device_status_reports')
    op.drop_index(op.f('ix_device_status_reports_id'), table_name='device_status_reports')
    op.drop_index(op.f('ix_device_status_reports_device_id'), table_name='device_status_reports')
    op.drop_table('device_status_reports')
    op.drop_index(op.f('ix_device_status_history_reported_at'), table_name='device_status_history')
    op.drop_index(op.f('ix_device_status_history_id'), table_name='device_status_history')
    op.drop_table('device_status_history')
    op.drop_index(op.f('ix_device_state_events_occurred_at'), table_name='device_state_events')
    op.drop_index(op.f('ix_device_state_events_id'), table_name='device_state_events')
    op.drop_index(op.f('ix_device_state_events_event_type'), table_name='device_state_events')
    op.drop_index(op.f('ix_device_state_events_device_id'), table_name='device_state_events')
    op.drop_table('device_state_events')
    op.drop_index(op.f('ix_area_job_images_job_id'), table_name='area_job_images')
    op.drop_index(op.f('ix_area_job_images_id'), table_name='area_job_images')
    op.drop_index(op.f('ix_area_job_images_created_at'), table_name='area_job_images')
    op.drop_table('area_job_images')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_config_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_code'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_area_jobs_status'), table_name='area_jobs')
    op.drop_index(op.f('ix_area_jobs_job_id'), table_name='area_jobs')
    op.drop_index(op.f('ix_area_jobs_id'), table_name='area_jobs')
    op.drop_index(op.f('ix_area_jobs_folder_name'), table_name='area_jobs')
    op.drop_index(op.f('ix_area_jobs_created_at'), table_name='area_jobs')
    op.drop_table('area_jobs')
    # ### end Alembic commands ###
