"""execution system schema

Revision ID: 0002_execution_system
Revises: 0001_legacy_baseline
Create Date: 2026-07-25 20:15:44.780314
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0002_execution_system'
down_revision: Union[str, Sequence[str], None] = '0001_legacy_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_categories_key'), 'execution_categories', ['key'], unique=True)
    op.create_table('execution_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_execution_outbox_aggregate_id'), 'execution_outbox', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_execution_outbox_dead_lettered_at'), 'execution_outbox', ['dead_lettered_at'], unique=False)
    op.create_index('ix_execution_outbox_dispatch', 'execution_outbox', ['dispatched_at', 'available_at', 'lease_expires_at'], unique=False)
    op.create_table('execution_login_throttles',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key_hash')
    )
    op.create_index(op.f('ix_execution_login_throttles_blocked_until'), 'execution_login_throttles', ['blocked_until'], unique=False)
    op.create_table('execution_worker_heartbeats',
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_index(op.f('ix_execution_worker_heartbeats_last_seen_at'), 'execution_worker_heartbeats', ['last_seen_at'], unique=False)
    op.create_table('execution_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_permissions_key'), 'execution_permissions', ['key'], unique=True)
    op.create_table('execution_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_roles_key'), 'execution_roles', ['key'], unique=True)
    op.create_table('execution_storage_roots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('root_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('access_mode', sa.String(length=20), nullable=False),
    sa.Column('category_key', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('availability_message', sa.Text(), nullable=True),
    sa.Column('scan_generation', sa.Integer(), nullable=False),
    sa.Column('last_scan_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_storage_roots_category_key'), 'execution_storage_roots', ['category_key'], unique=False)
    op.create_index(op.f('ix_execution_storage_roots_root_id'), 'execution_storage_roots', ['root_id'], unique=True)
    op.create_table('execution_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_users_role'), 'execution_users', ['role'], unique=False)
    op.create_index(op.f('ix_execution_users_username'), 'execution_users', ['username'], unique=True)
    op.create_table('execution_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['execution_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_audit_created', 'execution_audit_logs', ['created_at'], unique=False)
    op.create_index('ix_execution_audit_resource', 'execution_audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('execution_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('system_key', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['execution_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'system_key', name='uq_execution_credentials_user_system')
    )
    op.create_index(op.f('ix_execution_credentials_user_id'), 'execution_credentials', ['user_id'], unique=False)
    op.create_table('execution_file_index_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('storage_root_id', sa.String(length=36), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('extension', sa.String(length=30), nullable=False),
    sa.Column('file_kind', sa.String(length=50), nullable=False),
    sa.Column('inspection_number', sa.String(length=200), nullable=True),
    sa.Column('group_key', sa.String(length=500), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fingerprint', sa.String(length=200), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('scan_generation', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('missing_since', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['storage_root_id'], ['execution_storage_roots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_root_id', 'relative_path', name='uq_execution_file_index_root_path')
    )
    op.create_index(op.f('ix_execution_file_index_entries_extension'), 'execution_file_index_entries', ['extension'], unique=False)
    op.create_index(op.f('ix_execution_file_index_entries_file_kind'), 'execution_file_index_entries', ['file_kind'], unique=False)
    op.create_index(op.f('ix_execution_file_index_entries_filename'), 'execution_file_index_entries', ['filename'], unique=False)
    op.create_index(op.f('ix_execution_file_index_entries_group_key'), 'execution_file_index_entries', ['group_key'], unique=False)
    op.create_index(op.f('ix_execution_file_index_entries_inspection_number'), 'execution_file_index_entries', ['inspection_number'], unique=False)
    op.create_index(op.f('ix_execution_file_index_entries_missing_since'), 'execution_file_index_entries', ['missing_since'], unique=False)
    op.create_index(op.f('ix_execution_file_index_entries_modified_at'), 'execution_file_index_entries', ['modified_at'], unique=False)
    op.create_index(op.f('ix_execution_file_index_entries_scan_generation'), 'execution_file_index_entries', ['scan_generation'], unique=False)
    op.create_index(op.f('ix_execution_file_index_entries_storage_root_id'), 'execution_file_index_entries', ['storage_root_id'], unique=False)
    op.create_index('ix_execution_file_index_group', 'execution_file_index_entries', ['storage_root_id', 'group_key'], unique=False)
    op.create_index('ix_execution_file_index_lookup', 'execution_file_index_entries', ['storage_root_id', 'inspection_number', 'modified_at'], unique=False)
    op.create_table('execution_index_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('storage_root_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=True),
    sa.Column('added_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('removed_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['execution_users.id'], ),
    sa.ForeignKeyConstraint(['storage_root_id'], ['execution_storage_roots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_index_jobs_claim', 'execution_index_jobs', ['status', 'created_at', 'lease_expires_at'], unique=False)
    op.create_index(
        'uq_execution_index_jobs_active_root',
        'execution_index_jobs',
        ['storage_root_id'],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
        sqlite_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index(op.f('ix_execution_index_jobs_lease_expires_at'), 'execution_index_jobs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_execution_index_jobs_status'), 'execution_index_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_execution_index_jobs_storage_root_id'), 'execution_index_jobs', ['storage_root_id'], unique=False)
    op.create_table('execution_role_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['execution_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['execution_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_execution_role_permission')
    )
    op.create_index(op.f('ix_execution_role_permissions_permission_id'), 'execution_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_execution_role_permissions_role_id'), 'execution_role_permissions', ['role_id'], unique=False)
    op.create_table('execution_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['execution_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_sessions_expires_at'), 'execution_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_execution_sessions_token_hash'), 'execution_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_execution_sessions_user_id'), 'execution_sessions', ['user_id'], unique=False)
    op.create_table('execution_user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['execution_users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['execution_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['execution_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_execution_user_role')
    )
    op.create_index(op.f('ix_execution_user_roles_role_id'), 'execution_user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_execution_user_roles_user_id'), 'execution_user_roles', ['user_id'], unique=False)
    op.create_table('execution_workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('draft_definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('draft_revision', sa.Integer(), nullable=False),
    sa.Column('published_version_number', sa.Integer(), nullable=True),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('required_input_count', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('availability_code', sa.String(length=100), nullable=True),
    sa.Column('availability_message', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['execution_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['execution_users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['execution_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_workflows_category_id'), 'execution_workflows', ['category_id'], unique=False)
    op.create_index(op.f('ix_execution_workflows_slug'), 'execution_workflows', ['slug'], unique=True)
    op.create_index(op.f('ix_execution_workflows_updated_at'), 'execution_workflows', ['updated_at'], unique=False)
    op.create_table('execution_workflow_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('release_note', sa.Text(), nullable=True),
    sa.Column('published_by_id', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['published_by_id'], ['execution_users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['execution_workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version_number', name='uq_execution_workflow_versions_number')
    )
    op.create_index('ix_execution_workflow_versions_checksum', 'execution_workflow_versions', ['workflow_id', 'checksum'], unique=False)
    op.create_index(op.f('ix_execution_workflow_versions_workflow_id'), 'execution_workflow_versions', ['workflow_id'], unique=False)
    op.create_table('execution_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('inspection_number', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('definition_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('definition_checksum', sa.String(length=64), nullable=False),
    sa.Column('input_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('global_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('output_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['execution_users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['execution_workflows.id'], ),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['execution_workflow_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by_id', 'idempotency_key', name='uq_execution_runs_creator_idempotency')
    )
    op.create_index(op.f('ix_execution_runs_created_by_id'), 'execution_runs', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_execution_runs_inspection_number'), 'execution_runs', ['inspection_number'], unique=False)
    op.create_index(op.f('ix_execution_runs_status'), 'execution_runs', ['status'], unique=False)
    op.create_index('ix_execution_runs_status_created', 'execution_runs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_execution_runs_updated_at'), 'execution_runs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_execution_runs_workflow_id'), 'execution_runs', ['workflow_id'], unique=False)
    op.create_index(op.f('ix_execution_runs_workflow_version_id'), 'execution_runs', ['workflow_version_id'], unique=False)
    op.create_table('execution_edge_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('edge_id', sa.String(length=100), nullable=False),
    sa.Column('source_node_id', sa.String(length=100), nullable=False),
    sa.Column('target_node_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('join_policy', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['execution_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'edge_id', name='uq_execution_edge_runs_run_edge')
    )
    op.create_index(op.f('ix_execution_edge_runs_run_id'), 'execution_edge_runs', ['run_id'], unique=False)
    op.create_index('ix_execution_edge_runs_target', 'execution_edge_runs', ['run_id', 'target_node_id', 'status'], unique=False)
    op.create_table('execution_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['execution_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_execution_events_event_type'), 'execution_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_execution_events_run_id'), 'execution_events', ['run_id'], unique=False)
    op.create_index('ix_execution_events_run_id_id', 'execution_events', ['run_id', 'id'], unique=False)
    op.create_table('execution_node_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('node_type', sa.String(length=100), nullable=False),
    sa.Column('node_type_version', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('output_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['execution_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'node_id', name='uq_execution_node_runs_run_node')
    )
    op.create_index('ix_execution_node_runs_claim', 'execution_node_runs', ['status', 'ready_at', 'lease_expires_at'], unique=False)
    op.create_index(op.f('ix_execution_node_runs_lease_expires_at'), 'execution_node_runs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_execution_node_runs_run_id'), 'execution_node_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_execution_node_runs_status'), 'execution_node_runs', ['status'], unique=False)
    op.create_table('execution_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('node_run_id', sa.String(length=36), nullable=True),
    sa.Column('storage_root_id', sa.String(length=36), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('media_type', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_run_id'], ['execution_node_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['execution_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['storage_root_id'], ['execution_storage_roots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'storage_root_id', 'relative_path', 'content_sha256', name='uq_execution_artifact_identity')
    )
    op.create_index(op.f('ix_execution_artifacts_content_sha256'), 'execution_artifacts', ['content_sha256'], unique=False)
    op.create_index(op.f('ix_execution_artifacts_node_run_id'), 'execution_artifacts', ['node_run_id'], unique=False)
    op.create_index(op.f('ix_execution_artifacts_role'), 'execution_artifacts', ['role'], unique=False)
    op.create_index(op.f('ix_execution_artifacts_run_id'), 'execution_artifacts', ['run_id'], unique=False)
    op.create_index('ix_execution_artifacts_run_role', 'execution_artifacts', ['run_id', 'role'], unique=False)
    op.create_index(op.f('ix_execution_artifacts_storage_root_id'), 'execution_artifacts', ['storage_root_id'], unique=False)
    op.create_table('execution_human_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('node_run_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('form_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('draft_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_role_key', sa.String(length=50), nullable=True),
    sa.Column('claimed_by_id', sa.String(length=36), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by_id', sa.String(length=36), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['execution_users.id'], ),
    sa.ForeignKeyConstraint(['claimed_by_id'], ['execution_users.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['execution_users.id'], ),
    sa.ForeignKeyConstraint(['node_run_id'], ['execution_node_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['execution_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_human_tasks_assigned_user_id'), 'execution_human_tasks', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_execution_human_tasks_candidate_role_key'), 'execution_human_tasks', ['candidate_role_key'], unique=False)
    op.create_index(op.f('ix_execution_human_tasks_node_run_id'), 'execution_human_tasks', ['node_run_id'], unique=True)
    op.create_index(op.f('ix_execution_human_tasks_run_id'), 'execution_human_tasks', ['run_id'], unique=False)
    op.create_index(op.f('ix_execution_human_tasks_status'), 'execution_human_tasks', ['status'], unique=False)
    op.create_table('execution_node_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('node_run_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('lease_token', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('output_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['node_run_id'], ['execution_node_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_run_id', 'attempt_number', name='uq_execution_node_attempts_number')
    )
    op.create_index(op.f('ix_execution_node_attempts_node_run_id'), 'execution_node_attempts', ['node_run_id'], unique=False)
    op.create_table('execution_artifact_relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('child_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['child_artifact_id'], ['execution_artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['execution_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_artifact_id', 'child_artifact_id', 'relation_type', name='uq_execution_artifact_relation')
    )
    op.create_index(op.f('ix_execution_artifact_relations_child_artifact_id'), 'execution_artifact_relations', ['child_artifact_id'], unique=False)
    op.create_index(op.f('ix_execution_artifact_relations_parent_artifact_id'), 'execution_artifact_relations', ['parent_artifact_id'], unique=False)
    op.create_table('execution_file_mutations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mutation_id', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('node_run_id', sa.String(length=36), nullable=True),
    sa.Column('source_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('working_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source_fingerprint', sa.String(length=200), nullable=False),
    sa.Column('change_plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verification_result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_run_id'], ['execution_node_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['execution_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['execution_artifacts.id'], ),
    sa.ForeignKeyConstraint(['working_artifact_id'], ['execution_artifacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_file_mutations_mutation_id'), 'execution_file_mutations', ['mutation_id'], unique=True)
    op.create_index(op.f('ix_execution_file_mutations_node_run_id'), 'execution_file_mutations', ['node_run_id'], unique=False)
    op.create_index(op.f('ix_execution_file_mutations_run_id'), 'execution_file_mutations', ['run_id'], unique=False)
    op.create_index(op.f('ix_execution_file_mutations_status'), 'execution_file_mutations', ['status'], unique=False)
    op.create_table('execution_publish_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mutation_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('target_storage_root_id', sa.String(length=36), nullable=False),
    sa.Column('target_relative_path', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('published_by_id', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['execution_artifacts.id'], ),
    sa.ForeignKeyConstraint(['mutation_id'], ['execution_file_mutations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by_id'], ['execution_users.id'], ),
    sa.ForeignKeyConstraint(['target_storage_root_id'], ['execution_storage_roots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mutation_id', 'target_storage_root_id', 'target_relative_path', name='uq_execution_publish_receipt_target')
    )
    op.create_index(op.f('ix_execution_publish_receipts_mutation_id'), 'execution_publish_receipts', ['mutation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_publish_receipts_mutation_id'), table_name='execution_publish_receipts')
    op.drop_table('execution_publish_receipts')
    op.drop_index(op.f('ix_execution_file_mutations_status'), table_name='execution_file_mutations')
    op.drop_index(op.f('ix_execution_file_mutations_run_id'), table_name='execution_file_mutations')
    op.drop_index(op.f('ix_execution_file_mutations_node_run_id'), table_name='execution_file_mutations')
    op.drop_index(op.f('ix_execution_file_mutations_mutation_id'), table_name='execution_file_mutations')
    op.drop_table('execution_file_mutations')
    op.drop_index(op.f('ix_execution_artifact_relations_parent_artifact_id'), table_name='execution_artifact_relations')
    op.drop_index(op.f('ix_execution_artifact_relations_child_artifact_id'), table_name='execution_artifact_relations')
    op.drop_table('execution_artifact_relations')
    op.drop_index(op.f('ix_execution_node_attempts_node_run_id'), table_name='execution_node_attempts')
    op.drop_table('execution_node_attempts')
    op.drop_index(op.f('ix_execution_human_tasks_status'), table_name='execution_human_tasks')
    op.drop_index(op.f('ix_execution_human_tasks_candidate_role_key'), table_name='execution_human_tasks')
    op.drop_index(op.f('ix_execution_human_tasks_assigned_user_id'), table_name='execution_human_tasks')
    op.drop_index(op.f('ix_execution_human_tasks_run_id'), table_name='execution_human_tasks')
    op.drop_index(op.f('ix_execution_human_tasks_node_run_id'), table_name='execution_human_tasks')
    op.drop_table('execution_human_tasks')
    op.drop_index(op.f('ix_execution_artifacts_storage_root_id'), table_name='execution_artifacts')
    op.drop_index('ix_execution_artifacts_run_role', table_name='execution_artifacts')
    op.drop_index(op.f('ix_execution_artifacts_run_id'), table_name='execution_artifacts')
    op.drop_index(op.f('ix_execution_artifacts_role'), table_name='execution_artifacts')
    op.drop_index(op.f('ix_execution_artifacts_node_run_id'), table_name='execution_artifacts')
    op.drop_index(op.f('ix_execution_artifacts_content_sha256'), table_name='execution_artifacts')
    op.drop_table('execution_artifacts')
    op.drop_index(op.f('ix_execution_node_runs_status'), table_name='execution_node_runs')
    op.drop_index(op.f('ix_execution_node_runs_run_id'), table_name='execution_node_runs')
    op.drop_index(op.f('ix_execution_node_runs_lease_expires_at'), table_name='execution_node_runs')
    op.drop_index('ix_execution_node_runs_claim', table_name='execution_node_runs')
    op.drop_table('execution_node_runs')
    op.drop_index('ix_execution_events_run_id_id', table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_run_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_event_type'), table_name='execution_events')
    op.drop_table('execution_events')
    op.drop_index('ix_execution_edge_runs_target', table_name='execution_edge_runs')
    op.drop_index(op.f('ix_execution_edge_runs_run_id'), table_name='execution_edge_runs')
    op.drop_table('execution_edge_runs')
    op.drop_index(op.f('ix_execution_runs_workflow_version_id'), table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_workflow_id'), table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_updated_at'), table_name='execution_runs')
    op.drop_index('ix_execution_runs_status_created', table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_status'), table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_inspection_number'), table_name='execution_runs')
    op.drop_index(op.f('ix_execution_runs_created_by_id'), table_name='execution_runs')
    op.drop_table('execution_runs')
    op.drop_index(op.f('ix_execution_workflow_versions_workflow_id'), table_name='execution_workflow_versions')
    op.drop_index('ix_execution_workflow_versions_checksum', table_name='execution_workflow_versions')
    op.drop_table('execution_workflow_versions')
    op.drop_index(op.f('ix_execution_workflows_updated_at'), table_name='execution_workflows')
    op.drop_index(op.f('ix_execution_workflows_slug'), table_name='execution_workflows')
    op.drop_index(op.f('ix_execution_workflows_category_id'), table_name='execution_workflows')
    op.drop_table('execution_workflows')
    op.drop_index(op.f('ix_execution_user_roles_user_id'), table_name='execution_user_roles')
    op.drop_index(op.f('ix_execution_user_roles_role_id'), table_name='execution_user_roles')
    op.drop_table('execution_user_roles')
    op.drop_index(op.f('ix_execution_sessions_user_id'), table_name='execution_sessions')
    op.drop_index(op.f('ix_execution_sessions_token_hash'), table_name='execution_sessions')
    op.drop_index(op.f('ix_execution_sessions_expires_at'), table_name='execution_sessions')
    op.drop_table('execution_sessions')
    op.drop_index(op.f('ix_execution_role_permissions_role_id'), table_name='execution_role_permissions')
    op.drop_index(op.f('ix_execution_role_permissions_permission_id'), table_name='execution_role_permissions')
    op.drop_table('execution_role_permissions')
    op.drop_index(op.f('ix_execution_index_jobs_storage_root_id'), table_name='execution_index_jobs')
    op.drop_index('uq_execution_index_jobs_active_root', table_name='execution_index_jobs')
    op.drop_index(op.f('ix_execution_index_jobs_status'), table_name='execution_index_jobs')
    op.drop_index(op.f('ix_execution_index_jobs_lease_expires_at'), table_name='execution_index_jobs')
    op.drop_index('ix_execution_index_jobs_claim', table_name='execution_index_jobs')
    op.drop_table('execution_index_jobs')
    op.drop_index('ix_execution_file_index_lookup', table_name='execution_file_index_entries')
    op.drop_index('ix_execution_file_index_group', table_name='execution_file_index_entries')
    op.drop_index(op.f('ix_execution_file_index_entries_storage_root_id'), table_name='execution_file_index_entries')
    op.drop_index(op.f('ix_execution_file_index_entries_scan_generation'), table_name='execution_file_index_entries')
    op.drop_index(op.f('ix_execution_file_index_entries_modified_at'), table_name='execution_file_index_entries')
    op.drop_index(op.f('ix_execution_file_index_entries_missing_since'), table_name='execution_file_index_entries')
    op.drop_index(op.f('ix_execution_file_index_entries_inspection_number'), table_name='execution_file_index_entries')
    op.drop_index(op.f('ix_execution_file_index_entries_group_key'), table_name='execution_file_index_entries')
    op.drop_index(op.f('ix_execution_file_index_entries_filename'), table_name='execution_file_index_entries')
    op.drop_index(op.f('ix_execution_file_index_entries_file_kind'), table_name='execution_file_index_entries')
    op.drop_index(op.f('ix_execution_file_index_entries_extension'), table_name='execution_file_index_entries')
    op.drop_table('execution_file_index_entries')
    op.drop_index(op.f('ix_execution_credentials_user_id'), table_name='execution_credentials')
    op.drop_table('execution_credentials')
    op.drop_index('ix_execution_audit_resource', table_name='execution_audit_logs')
    op.drop_index('ix_execution_audit_created', table_name='execution_audit_logs')
    op.drop_table('execution_audit_logs')
    op.drop_index(op.f('ix_execution_users_username'), table_name='execution_users')
    op.drop_index(op.f('ix_execution_users_role'), table_name='execution_users')
    op.drop_table('execution_users')
    op.drop_index(op.f('ix_execution_storage_roots_root_id'), table_name='execution_storage_roots')
    op.drop_index(op.f('ix_execution_storage_roots_category_key'), table_name='execution_storage_roots')
    op.drop_table('execution_storage_roots')
    op.drop_index(op.f('ix_execution_roles_key'), table_name='execution_roles')
    op.drop_table('execution_roles')
    op.drop_index(op.f('ix_execution_permissions_key'), table_name='execution_permissions')
    op.drop_table('execution_permissions')
    op.drop_index(op.f('ix_execution_login_throttles_blocked_until'), table_name='execution_login_throttles')
    op.drop_table('execution_login_throttles')
    op.drop_index(op.f('ix_execution_worker_heartbeats_last_seen_at'), table_name='execution_worker_heartbeats')
    op.drop_table('execution_worker_heartbeats')
    op.drop_index('ix_execution_outbox_dispatch', table_name='execution_outbox')
    op.drop_index(op.f('ix_execution_outbox_dead_lettered_at'), table_name='execution_outbox')
    op.drop_index(op.f('ix_execution_outbox_aggregate_id'), table_name='execution_outbox')
    op.drop_table('execution_outbox')
    op.drop_index(op.f('ix_execution_categories_key'), table_name='execution_categories')
    op.drop_table('execution_categories')
    # ### end Alembic commands ###
